version: '1.0'
services:
  aggr:
    build: ./aggr                     # Builds from Dockerfile in this specified directory
    image: bradrut/aggr:3.3.2
    ports:
      - "3000:80"                     # Host:App
  aggr-redis:
    build: ./aggr-redis
    image: bradrut/aggr-redi:1.0.0
    ports:
      - "6379:6379"
  aggr-telegram-service:
    build: ./aggr-telegram-service
    image: bradrut/aggr-telegram-service:1.0.0
    ports:
      - "3001:3000"
    depends_on:
      aggr-redis:
        condition: service_started
        restart: true