services:
  aggr-telegram-service:
    build: ./aggr-telegram-service    # Builds from Dockerfile in this specified directory
    ports:
      - "3000:3000"                   # Host:app
  aggr-redis:
    build: ./aggr-redis
    ports:
      - "6379:6379"